### ISSUE TITLE
[bat] Batch file syntax highlighting works incorrectly for single-letter variables

### ISSUE THREAD

**Issue by aeschli** [mmims/language-batchfile#25] opened 2018-02-19 08:46 UTC
_From @m93a on February 18, 2018 11:36_

- VSCode Version: 1.20.0
- OS Version: Windows 10 Pro 1709

Steps to Reproduce:

1. Create a `.bat` file
2. Either use a single-letter variable outside of a string
2. Or use two single-letter variables inside strings on the same line

![image](https://user-images.githubusercontent.com/1671665/36351291-c1359794-14a7-11e8-830e-aecd17408976.png)

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#43923_

**Comment by mmims** [comment] 2018-02-22 20:32
Duplicate of #24.

**Comment by mmims** [comment] 2018-02-23 19:21
This issue will require creating a new pattern and subpatterns to handle for loops properly. A temporary fix will be provided when the fix for #24 is committed.

**Comment by msftrncs** [comment] 2018-06-21 00:38
Can I also add:
![image](https://user-images.githubusercontent.com/26179051/41691607-1089a212-74c1-11e8-8d88-61d913c50f2b.png)
and
![image](https://user-images.githubusercontent.com/26179051/41691657-3c338d10-74c1-11e8-9ab9-2c8ea098f5b1.png)
(from VSCode 1.24.1)

**Closed as completed** 2021-04-22 02:44 UTC
